seed: 0
phys_nn_config: 3
physics_model: sindy
predict_delta: false
model_kwargs:
  backend: torch
  predict_delta: false
  noise_level: 0.0
trial_length: 200
num_trials: 10
num_particles: 20
ensemble_size: 5
pretrain_trial_length: 200
defaults: 
 - dynamics: GaussianMLP
 - optimizer: CEM
 - agent: TrajectoryOptimizerAgent
 - env: cartpole
