seed: 0
phys_nn_config: 3
physics_model: sindy
model_kwargs:
  backend: torch
  predict_delta: True
  noise_level: 0.0
trial_length: 200
num_trials: 10
num_particles: 20
ensemble_size: 5
defaults: 
 - dynamics: GaussianMLP
 - agent: TrajectoryOptimizerAgent
 - optimizer: CEM